# Generated by Django 4.0.4 on 2022-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('type', models.IntegerField(choices=[[1, 'Consulta'], [2, 'Sugerencia'], [3, 'Error'], [4, 'Otro']], verbose_name='')),
                ('message', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
